version: '3'
services:
  proxy:
    image: nginx
    ports:
      - ${WEB_PORT}

  api-php-fpm:
    image: icanmake-api-php-fpm
    build:
      context: api
      dockerfile: docker/production/php-fpm/Dockerfile

  postgres:
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}