version: '3'
services:
  proxy:
    image: nginx:alpine
    volumes:
      - ./api/docker/development/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${WEB_PORT}
    depends_on:
      - api-php-fpm

  api-php-fpm:
    build:
      context: api/docker/development/php-fpm
    volumes:
      - ./api:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:16.0-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - ${ADMINER_PORT}

